### ISSUE TITLE
"custom" field in save/load json

### ISSUE THREAD

**Issue by alex9311** [xyonix/vannot#11]
we should be able to load from a json
```
{
  "custom": {"internal_id": "foobar"}
  "video": {
    "fps": 25,
    "duration": 125100,
    "width": 1920,
    "height": 1080,
    "source": "my_video.mp4"
  },
  "saveUrl": "my_save_url",
}
```

and have that field persist upon saving. The custom field should hold whatever object.

Does that make sense?

**Comment by alex9311** [comment]
this is a blocker

**Comment by clint-tseng** [comment]
This should work as described, actually. Does the field disappear when you try?

**Comment by alex9311** [comment]
Hi Clint,

Thanks! I haven't tried myself yet, I didn't think it would work without a code change. Great!
