### ISSUE TITLE
start/stop times on video

### ISSUE THREAD

**Issue by alex9311** [xyonix/vannot#12]
some of our videos are several hours. We'd like to be able to specify a subpart of the video to be displayed on vannot.

```
{
  "video": { 
    "fps": 25,
    "duration": 125100,
    "width": 1920,
    "height": 1080,
    "source": "my_video.mp4",
    "startSeconds": 100,
    "endSeconds": 900
  },
  "saveUrl": "my_save_url",
}

**Comment by alex9311** [comment]
this is a blocker

**Comment by clint-tseng** [comment]
This makes a lot of sense; I'd figured you'd want something like this but I wasn't sure how you wanted to configure it. Should be pretty straightforward to add. Thanks!

**Comment by alex9311** [comment]
hey @clint-tseng , it looks like the video is starting and the timeline displays as expected. However, if I press play and let it go, the video will keep on running past duration (out of the range of the scrub bar)

**Comment by clint-tseng** [comment]
Ha, okay; I'll take a look.
