### ISSUE TITLE
Results Cannot Be Saved

### ISSUE THREAD

**Issue by chasemaier** [xyonix/vannot#17]
Clicking save shows "Please wait..." toast, but generates the following error.

```
Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at wait (app.js:50312:30)
    at inner (app.js:50303:59)
```

**Comment by clint-tseng** [comment]
This is a security error of some kind. Is the video being loaded from a different origin domain than the app? We may have to include a restriction that they be from the same source, as the browser imposes various restrictions hereof.

**Comment by chasemaier** [comment]
Yes, the video is from a CORS-enabled S3 bucket.

Requiring co-location of the video and UI doesn't seem like a practical path forward. We have hundreds of TBs of videos in various origins we'd want to support.

I'll see if I can submit a PR to resolve this particular error.

**Comment by chasemaier** [comment]
Resolved by https://github.com/xyonix/vannot/pull/18
