### ISSUE TITLE
carry-over breaks when objects are grouped

### ISSUE THREAD

**Issue by alex9311** [xyonix/vannot#32]
sometimes the objects dont show up at all. When they do, they cannot be moved or modified

https://vannot.csats.pizza/?data=https://vannot-state.csats.pizza/_example/sample-01

**Comment by clint-tseng** [comment]
hey alex; i believe this was fixed in https://github.com/xyonix/vannot/commit/750af0c92c3a05617381b2ba895ebcb4cf1b5ac4

looking over the code you have deployed in that instance, it doesn't look like it's got that commit in there.

**Comment by alex9311** [comment]
oh my bad, we will redeploy and I'll update this issue

**Comment by alex9311** [comment]
looks good! Thanks
