### ISSUE TITLE
hotkeys

### ISSUE THREAD

**Issue by alex9311** [xyonix/vannot#33]
is there some way to enter the image and zoom it to 100% or screen width? I thought there was a hotkey for that

**Comment by clint-tseng** [comment]
not yet, but we can very definitely add a "zoom-to-origin" sort of hotkey. any suggestions on what it should be? i think ctrl+zero is pretty common but that's also overloaded with the browser already. perhaps simply the number zero so long as a text input isn't highlighted, but that might be confusing.

**Comment by alex9311** [comment]
Hey thanks for the quick response. How about double clicking the pan tool? Or double tapping the space bar? Since that activates the pan.

In my mind the pan would be related to resetting zoom/center.

Could also be a button between zoom and the select/pan buttons. Then hotkey info on hover?

/shrug

**Comment by clint-tseng** [comment]
double-tapping space seems really reasonable; we'll go with that. i'll see if i can get it in there today or monday, should be pretty quick to do. and adding a button there with the hotkey info is a great idea too.

**Comment by clint-tseng** [comment]
alright; i pushed something for this to master. give it a try when you get a chance!

**Comment by alex9311** [comment]
woops I think that broke the quick-pan, holding space must register the same as double tapping the space bar. Sorry I didnt think of that!

**Comment by clint-tseng** [comment]
ah shoot. no, that just means i did a bad job. pushed again.

**Comment by alex9311** [comment]
great, that is super helpful! Thank you
