### ISSUE TITLE
vertex dots too big

### ISSUE THREAD

**Issue by alex9311** [xyonix/vannot#34]
I'm having problems when annotating if I have a border with a lot of edges. The dots obscure each other, and the problem is compounded by the dots that show up in the middle of each edge. 

In the screenshot below, it is super easy to accidentally split an edge in two when trying to drag move a vertice. Does that make sense? A suggested solution would be to make the dots smaller when zoomed in but I'm open to ideas of course

![dots](https://user-images.githubusercontent.com/1326899/43019437-d050b22c-8c11-11e8-93a0-8e7612fee536.png)

**Comment by chasemaier** [comment]
@alex9311 See https://github.com/xyonix/vannot/issues/31. Give that branch a run locally and see if the performance considerations are a concern or not.

**Comment by alex9311** [comment]
thanks chase, I'll move to that issue. Closing
