### ISSUE TITLE
Changing shape focus with instance group edit focused applies value to wrong shape

### ISSUE THREAD

**Issue by chasemaier** [xyonix/vannot#35]
1. Create two labeled instance groups. E.g. Apply class "A" to the first one and "B" to the second, in that order.
1. De-select all objects.
1. Select instance "A" again.

In this case, the drop-down for the instance class label will show "B" since it is the most recently selected item in the drop-down.

I believe this should always sync up with the current value of the selected instance and instead show the corresponding label as the `selected` option (in this case "A").

**Comment by clint-tseng** [comment]
Hmmm, I'm unable to reproduce this with those steps. How many objects per group? Any other details? Does it always happen?

When I go back to either instance group it always reads the thing I assigned it.

**Comment by chasemaier** [comment]
Yeah, it always happens.

This is a poor demonstration, because the screen recorder doesn't capture when i open the actual dropdown (native element, so it doesn't get recorded).

The best thing I can point to in this video is immediately upon creating the instance group for the single polygon the dropdown is already selected to the last used item (I never assigned a value, should be unassigned by default for a new group).

https://drive.google.com/file/d/1N0Rs-SIXhh8-U-o60zvjZIaSETjDBa5v/view?usp=sharing

The end of the video shows that if i relabel the second group (single object) and then return focus to the first object, the group class doesn't change.

Let me know when you're done and I'll remove this shared file.

**Comment by clint-tseng** [comment]
Looks like I need access; request sent.

**Comment by chasemaier** [comment]
Oops, weird. Accepted that request.

**Comment by chasemaier** [comment]
I think it's a `.webm`. Played okay for me in VLC on windows/linux and also looks like Chrome can play it directly just dragging the file into a chrome tab.

**Comment by clint-tseng** [comment]
Okay, VLC+.webm did the trick, thanks. I see what you're saying in the video; I'll take a look tomorrow.

**Comment by clint-tseng** [comment]
Sigh, it's Firefox.

**Comment by clint-tseng** [comment]
Okay. What was happening was that because Firefox fires some events backwards, the very last change event on the combobox would apply to the newly selected shape instead of the previously selected one.

The fix is a hack but should work on any remotely modern browser. It's been pushed to master.

**Comment by chasemaier** [comment]
Hmm. I pulled the most recent commit in -- I'm still seeing the same issue in Chrome.

Also just checked Firefox since you mentioned it, same issue present there too.

**Comment by clint-tseng** [comment]
that’s odd. i never got it to repro in chrome, only firefox; and i tried
chrome/firefox afterwards and they definitely worked. so i’m inclined at
this point to believe it’s a platform-specific issue.

i’m out of town on leave through tuesday, but what are you on?

**Comment by clint-tseng** [comment]
Okay, I still cannot reproduce this but I just pushed a commit that I think has a reasonable shot at resolving your issue. Give it a try?

**Comment by chasemaier** [comment]
Nope. No luck.

Looking at the commit you added, it doesn't seem like that would be an applicable change to this problem as there isn't a problem with the dropdown registering change events -- that works fine.

The problem is with the dropdown not updating to reflect the selected data (i.e. upon some external event -- say polygon selection -- the selected option in the select would be changed). E.g. I click "polygon A", I'd expect the dropdown to show the class that was previously assigned to the group that that polygon belongs to rather than just the  Instead, it only ever shows the value the USER last selected.

**Comment by alex9311** [comment]
Are you on a Mac @clint-tseng ? I just tested it in browser stack and there is no repro on chrome in osx. I do see a repro on chrome on ubuntu

**Comment by clint-tseng** [comment]
So, I'm no longer sure what's going on here. I have tried this on Windows 10 with Chrome 68 and Firefox 61 and no matter how hard I try to abuse that dropdown I can't seem to get it to exhibit the behavior you're seeing.

My greatest remaining suspicion is that it has something to do with your data. Do you get any JS errors when the bug occurs?

**Comment by chasemaier** [comment]
Took me way too long to track this down, but think I've got a pretty specific idea now:

In `updateInstanceToolbar` you have a block like:
```js
    if ((canvas.selected.instance != null) && (canvas.instanceMode !== 'none')) {
      toolbar.select('.vannot-toolbar-instance-class').classed('visible', true);
      toolbar.select('.vannot-instance-class').node().value = canvas.selected.instance.class || '';
    } else ...
```

The last line of code there looks like the problem. Whatever the select function is doing, looks like it only gets one/a single DOM element it's interested in, which in this case is the wrong one.

It's interacting with `INPUT.vannot-instance-class`, not `SELECT.vannot-instance-class`.

![image](https://user-images.githubusercontent.com/2565985/44603502-c150d300-a797-11e8-8391-a3bc97c20848.png)

Changing the selector to `select.vannot-instance-class` on that line results in the selected value changing as a click on different instance groups.

Does that help at all?

**Comment by clint-tseng** [comment]
Bah! That's the one. Need to update both those controls. Thanks!

So the problem, then, was I never had the `instanceClass.mode` set to `preset`.

**Comment by clint-tseng** [comment]
(and I guess the other bug I found is specific to the mode _not_ being set to preset)

**Comment by clint-tseng** [comment]
okay, i've pushed a fix for this one. thanks for helping track it down; i didn't catch the crucial detail here.

fyi i also pushed a change that should somewhat improve your experience with zoom rates. it should help quite a bit, but i do need to make one more adjustment there before it works as desired in windows/linux.

**Comment by chasemaier** [comment]
Looks resolved. Thanks.
