### ISSUE TITLE
loading sometimes only works in incognito

### ISSUE THREAD

**Issue by alex9311** [xyonix/vannot#37]
Our annotators have been using incognito browsers because loading existing state sometimes doesn't work if they use a regular browser. The objects don't show in the timeline or on the video. No console errors. Something with caching? 

I don't have a consistent repro so I don't expect much, I will add details here if I get some. If you have any ideas with this limited bug report let me know!

**Comment by clint-tseng** [comment]
Huh. I am also curious why loading existing state doesn't work.. is there some way we can improve that situation so that incognito is not required?

And, when the objects don't show on the video, the video itself still does?

**Comment by alex9311** [comment]
Yeah the video itself loads fine. 

I'll work on getting a reliable repro

**Comment by alex9311** [comment]
just sent you an email with a link for repro

**Comment by alex9311** [comment]
I also noticed that when the loading fails, saving returns the error `Something went wrong trying to save data. Please check your connection and try again.`. 

What's funny is that even if the loading fails (no shapes appear), saving still pops up the dialogue "exporting frame 1 of 1" before the error message. So in some sense it seems to know there are frames to save

**Comment by clint-tseng** [comment]
I'm still thinking through this other piece of information you've given me, but I'm sorry to report that I've given the provided link a few dozen refreshes in non-incognito with chrome and safari and a mixture of soft and hard refreshes and it didn't fail a single time. Some particulars with network proximity and thus load order perhaps? I'm not sure.

**Comment by clint-tseng** [comment]
Are you sure you don't have some network/proxy caching layer on your side that's returning two different versions of the JSON payload for the same URL? And incognito resolves it due to.. I don't know, ETag or If-Match or modified date or something?

**Comment by clint-tseng** [comment]
Try comparing the actual downloaded data JSON when it "works" vs when it "doesn't" I think, and if they're the same we have some really strange ghosts and if they're not that's our clue.

**Comment by alex9311** [comment]
I can look into those suggestions.

Have you tried adding a shape, saving, closing the window, and reloading?

**Comment by clint-tseng** [comment]
Hm. When I do that it does what I'd expect, I think.

**Comment by clint-tseng** [comment]
Yeah, I did it a couple of times and it seems to work just fine for me. :/

**Comment by alex9311** [comment]
I checked the json file being loaded by the browser and it is _sometimes_ using a cached version even when the json object has been updated in s3.

Would you mind adding some version of 
```
  $.ajaxSetup({ cache: false });
```
to see if that solves our problems? Nothing in the app should use caching anyway

**Comment by clint-tseng** [comment]
yes! i’ll give that a try when i get my laptop back next week (apple has it
at the moment :/).

**Comment by alex9311** [comment]
our annotators report that the saving issues they were having are now solved! Guess it was a caching issue after all
