### ISSUE TITLE
hide/drag down bottom bar

### ISSUE THREAD

**Issue by alex9311** [xyonix/vannot#38]
We have a request from our annotators to be able to be able to drag to resize the area from the play buttons and below

![vannot](https://user-images.githubusercontent.com/1326899/47383901-8cd79580-d6ba-11e8-8c3c-edca2807be35.png)

**Comment by clint-tseng** [comment]
done, and pushed to master. give it a try, hope you like it?

**Comment by alex9311** [comment]
works great, thank you!
