### ISSUE TITLE
hotkey for carry over

### ISSUE THREAD

**Issue by alex9311** [xyonix/vannot#40]
our annotators have requested a hotkey for the carry over button, could you add that?

Are the current hotkeys documented anywhere? I haven't been able to find them

**Comment by clint-tseng** [comment]
yes, that can be added. there is not presently any central documentation; i
will start by adding it to the readme and then i will find some other spot
for them. i’ll get to this next week as apple _still_ has my laptop.
(grumble grumble)

**Comment by clint-tseng** [comment]
this is pushed to master now! it's ctrl+d (win) / cmd+d (mac)

**Comment by alex9311** [comment]
thanks Clint!
