### ISSUE TITLE
add counts of objects

### ISSUE THREAD

**Issue by alex9311** [xyonix/vannot#41]
Our annotators have requested some way of knowing how many of each object they have annotated. For example, showing a count next to each label on the left side of the timeline.

Instrument Tip (1)
Instrument Middle (0)
Instrument Shaft (0)

![vannot-timeline](https://user-images.githubusercontent.com/1326899/49395946-b689d080-f6ec-11e8-94b7-79391e7185f6.png)

**Comment by clint-tseng** [comment]
total? or in the current frame?

**Comment by alex9311** [comment]
total

**Comment by clint-tseng** [comment]
okay, pushed!

**Comment by alex9311** [comment]
looks great! Thanks!
